version: "3.9"

services:
  backend:
    build: .
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/whatsapp
    depends_on:
      - mongo
    networks:
      - chatnet

  mongo:
    image: mongo:6
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - chatnet

volumes:
  mongo_data:

networks:
  chatnet:
